Develop multi-modal basedataset and add the StrokePatientMIdataset based on it
torcheeg/torcheeg pull request #113
Opened 2024-05-30 12:18 UTC by arrogant-R

2024-06-05 02:57 UTC, arrogant-R commented
Fix some transforms and add constant of strokesmi]

2024-06-05 08:17 UTC, tczhangzhi requested changes
Thank you for your hard work and contribution. However, I suggest adding unit tests to your implementation to avoid potential errors. Additionally, as a toolkit rather than a personal project, we should consider generality and different scenarios when implementing. A simple tip is to avoid breaking changes to accommodate previously considered cases.

2024-06-05 08:17 UTC, tczhangzhi commented on torcheeg/transforms/numpy/downsample.py
> +        assert len(eeg.shape) == 2, 'Make sure the EEG in 2D shape.'
The EEG signals to be downsampled do not have to be 2D. A typical example is time series signals of different frequency bands represented by [frequency band, electrode, data point].

2024-06-05 08:17 UTC, tczhangzhi commented on torcheeg/transforms/any/baseline.py
> +         assert len(eeg.shape) == 2 and  len(kwargs['baseline'].shape) ==2, "Make sure EEG and its baseline in 2D shape. "
This implementation does not actually meet expectations. In many works, baseline removal is applied to features, corresponding to the average of high-order tensors along the segment dimension, e.g., [1]. This is also why we did not directly use the implementation from EEGLab.

Yang Y, Wu Q, Qiu M, et al. Emotion recognition from multi-channel EEG through parallel convolutional recurrent neural network[C]//2018 international joint conference on neural networks (IJCNN). IEEE, 2018: 1-7.

2024-06-05 08:17 UTC, tczhangzhi commented on torcheeg/datasets/module/motor_imagery/strokes.py
> +        self.electodes_info = pd.read_csv(os.path.join(
The electrode information should be defined as a constant. The event information should be read in process_record. This facilitates independent usage (only dependent on the cache).

2024-06-05 08:17 UTC, tczhangzhi commented on torcheeg/datasets/module/motor_imagery/strokes.py
> +class StrokePatientsMIDataset(BaseDataset):
Define two datasets: one is StrokePatientsMIDataset, and the other is StrokePatientsMIProcessedDataset. This helps with unit testing and distinguishing different hook behaviors.

2024-06-05 08:17 UTC, tczhangzhi commented on torcheeg/datasets/module/motor_imagery/strokes.py
> +        eeg = data[:, :30, :]
before_trial hook?

2024-06-05 08:17 UTC, tczhangzhi commented on torcheeg/datasets/module/__init__.py
> +from .base_multimodal import BaseMultiModalDataset
Please remove it.

2024-06-05 08:19 UTC, tczhangzhi commented on torcheeg/transforms/any/baseline.py
> +         assert len(eeg.shape) == 2 and  len(kwargs['baseline'].shape) ==2, "Make sure EEG and its baseline in 2D shape. "
Due to the complex related components, you can temporarily keep this part of the code. I will make the modifications.

2024-06-21 15:04 UTC, tczhangzhi commented
Thanks for your hard working and contribution, I like the implementation.

Overall, it works well. After I complete testing, I will consider merging it or adding comments.

2024-12-22 10:23 UTC, merged